<?php

/**
 * @file
 * Includes login window.
 */

?>
<?php //Show login block if user is not logged, otherwise - "logout" and "name". ?>
<?php if ($variables['is_logged']): ?>
    <div class="blocklogin">
      <form name="logout" action="/logout" method="POST">
        <label><?php print isset($variables['name']) ? $variables['name'] : ''; ?></label>
        <input type="submit" name="signout" value="Sign out" />
      </form>
    </div>
<?php else: ?>
  <div class="blocklogin">
    <form name="login" action="/login" method="POST">
      <div>
        <label>Login</label>
        <input type="text" name="login" placeholder="login"/>
      </div>
      <div>
        <label>Password</label>
        <input type="password" name="password" placeholder="password"/>
      </div>
        <input class="submit" type="submit" name="loginButton" value="Sign in"/>
    </form>
  </div>
<?php endif; ?>
